#!/bin/bash

# Set the process name
process_name=$1

# Check if the process is running
if pgrep -x "$process_name" > /dev/null
then
    echo "$process_name is already running"
else
    echo "$process_name is not running"
   
   # python3 /path/to/my_script.py &
fi