#!/usr/bin/env python3

import argparse
import subprocess
from colorama import Fore, Style, init
import sys

type_file="/home/yaniv/scripts-yaniv/guide/hash_mode.txt"
init()  # Initialize colorama to handle ANSI color codes on Windows and Unix
 

def analyze_hash(hashfile):
    try:
        with open(hashfile, 'r') as file:
            hash_value = file.read().strip()
    except FileNotFoundError:
        print("Hash file not found.")
        return
    except Exception as e:
        print(f"Failed to read the hash file: {e}")
        return

    # Executing hashid
    print(f"{Fore.GREEN}Output from hashid:{Style.RESET_ALL}")
    hashid_command = ["hashid", hashfile]
    hashid_output = subprocess.run(hashid_command, capture_output=True, text=True)
    filtered_output = '\n'.join(line for line in hashid_output.stdout.split('\n') if "Analyzing" not in line and "--" not in line)
    if filtered_output:
        print(filtered_output)
    else:
        print("Could not find from hashid.")

    # Executing Name That Hash
    print("\n")
    print(f"{Fore.BLUE}Most Likely hashes from nth:{Style.RESET_ALL}")
    nth_command = ["nth", "-f", hashfile]
    nth_output = subprocess.run(nth_command, capture_output=True, text=True)
    start = nth_output.stdout.find("Most Likely")
    end = nth_output.stdout.find("Least Likely")
    if start != -1 and end != -1:
        most_likely_section = nth_output.stdout[start:end].strip()
        print(most_likely_section)
    else:
        print("Could not find from nth.")

    # Executing hash-identifier
    print("\n")
    print(f"{Fore.YELLOW}Possible hashes from hash-identifier:{Style.RESET_ALL}")
    hash_identifier_command = ["hash-identifier"]
    process = subprocess.Popen(hash_identifier_command, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

    # Write to stdin and close it to signal EOF
    output, errors = process.communicate(input=hash_value + '\n', timeout=1)

    start = output.find("Possible Hashs:")
    end = output.find("Least Possible Hashs:")
    if start != -1 and end != -1:
        possible_hashes_section = output[start:end].strip()
        
        print(possible_hashes_section)
    else:
        print("Could not find from hash-identifier.")
    # If the process does not exit, kill it
    if process.poll() is None:
        process.kill()
        # print("hash-identifier process was terminated.")

    #excuting haiti
    print("\n")
    print(f"{Fore.CYAN}Possible hashes from haiti:{Style.RESET_ALL}")
    haiti_command = ["haiti", hash_value]
    haiti_output = subprocess.run(haiti_command, capture_output=True, text=True)
    print(haiti_output.stdout)

def choose_hash_type(filename, search_term):
    choice=0
    matching_lines = []
    try:
        with open(filename, 'r') as file:
            for line in file:
                if search_term.lower() in line.lower():
                    matching_lines.append(line.strip())
    except FileNotFoundError:
        print("The hash mode file was not found.")
        return None

    if not matching_lines:
        print(f"{Fore.RED}No matching hash types found for '{search_term}'{Style.RESET_ALL}")
        return None
    if len(matching_lines) == 1:
        chosen_line= matching_lines[0].split('|')[0].strip()
    else:
        for i, line in enumerate(matching_lines):
            print(f"{i + 1}. {line}")
        choice = int(input(f"{Fore.YELLOW}Choose a hash type (1-{len(matching_lines)}): {Style.RESET_ALL}"))
        chosen_line = matching_lines[choice - 1]
    hash_type_code = chosen_line.split('|')[0].strip()
    hash_type =matching_lines[choice - 1].split('|')[1].strip()
    return hash_type_code, hash_type

def get_hash(hashfile):
    try:
        with open(hashfile, 'r') as file:
            return file.read().strip()
    except FileNotFoundError:
        print("Hash file not found.")
        return None

def htj(hashcat_mode):
    hashcat_to_john = {
            '0': 'raw-md5',                      # MD5
            '100': 'nt',                         # NTLM
            '300': 'mssql',                      # MSSQL
            '400': 'raw-sha1',                   # SHA-1
            '500': 'md5crypt',                   # md5crypt, MD5(Unix), FreeBSD MD5, Cisco-IOS MD5
            '900': 'raw-md4',                    # MD4
            '1000': 'nt',                        # NTLM
            '1100': 'netntlmv2',                 # NTLMv2
            '1400': 'raw-sha256',                # SHA-256
            '1700': 'raw-sha512',                # SHA-512
            '1800': 'sha512crypt',               # sha512crypt, SHA512(Unix)
            '2100': 'mscash2',                   # Domain Cached Credentials 2, mscash2
            '3200': 'bcrypt',                    # bcrypt $2*$, Blowfish(Unix)
            '3710': 'md5-gen',                   # iSCSI CHAP authentication, MD5(Chap)
            '1500': 'descrypt',                  # DES(Unix)
            '16800': 'wpapmkid',                 # WPA/WPA2 PMKID
            '131': 'mssql12',                    # MSSQL 2012
            '3000': 'lm',                        # LM hashes
            '13400': 'krb5pa-sha1',              # Kerberos 5, etype 23, AS-REP
            '9900': 'racf',                      # RACF
            '11000': 'postgres',                 # PostgreSQL Challenge-Response Authentication (MD5)
            '6100': 'whirlpool',                 # Whirlpool
            '18800': 'pbkdf2-hmac-sha256',       # PBKDF2-HMAC-SHA256
            '18900': 'pbkdf2-hmac-sha512',       # PBKDF2-HMAC-SHA512
            '19000': 'pbkdf2-hmac-sha1',         # PBKDF2-HMAC-SHA1
            '19100': 'keychain',                 # Apple Keychain
            '19600': 'krb5tgs',                  # Kerberos 5, etype 17, TGS-REP
            '19800': 'krb5pa-sha1',              # Kerberos 5, etype 17, Pre-Auth
            '28800': 'krb5pa-sha1',              # Kerberos 5, etype 17, DB
            '19700': 'krb5tgs',                  # Kerberos 5, etype 18, TGS-REP
            '19900': 'krb5pa-sha1',              # Kerberos 5, etype 18, Pre-Auth
            '28900': 'krb5pa-sha1',              # Kerberos 5, etype 18, DB
            '7500': 'krb5pa-md5',                # Kerberos 5, etype 23, AS-REQ Pre-Auth
            '13100': 'krb5tgs',                  # Kerberos 5, etype 23, TGS-REP
            '18200': 'krb5asrep',                # Kerberos 5, etype 23, AS-REP
        }

    return hashcat_to_john.get(hashcat_mode, "Unknown Hashcat Mode")

def correct_hash_type(user_input):
    if user_input.startswith("sha-"):
        return user_input.replace("sha-", "sha2-")
    return user_input

def main():
    parser = argparse.ArgumentParser(description="This is a script for hashcat operations.")
    parser.add_argument("-f", "--hashfile", help="Path to the hash file", required=True)
    parser.add_argument("-t", "--hashtype", help="Optional hash type or part of it for searching", required=False)
    args = parser.parse_args()
    try:
        if args.hashtype:
            hash_type = choose_hash_type(type_file, args.hashtype)
            if not hash_type:
                return  # Exit if no hash type is found
        else:
            analyze_hash(args.hashfile)
            print("")
            user_hash_type = input(f"{Fore.CYAN}Enter the hash type name or part of it: {Style.RESET_ALL}")
            corrected_hash_type = correct_hash_type(user_hash_type)
          #  hash_type = choose_hash_type(type_file, corrected_hash_type)
            hash_type_code, hash_type = choose_hash_type(type_file, corrected_hash_type)
            if not hash_type_code:
                return  # Exit if no hash type is found

        hash_value = get_hash(args.hashfile)
        if hash_value:
            print(f"{Fore.MAGENTA}\nHash Value: {hash_value}{Style.RESET_ALL}")
            print(f"{Fore.MAGENTA}Hash Mode: {hash_type}{Style.RESET_ALL}")
            print(f"{Fore.MAGENTA}Hashcat Code for this type: {hash_type_code}{Style.RESET_ALL}")
            john_format = htj(hash_type_code)
            print(f"{Fore.MAGENTA}John the Ripper format this type: {john_format}{Style.RESET_ALL}")
        else:
            print("Could not read hash value from file.")

        
    except KeyboardInterrupt:
        print("\nbye..")
        sys.exit(1)

if __name__ == "__main__":
    main()
