#!/usr/bin/env python3
import sys

def check_rsa(key):
    start_index = key.find("-----BEGIN RSA PRIVATE KEY-----")
    end_index = key.find("-----END RSA PRIVATE KEY-----") + len("-----END RSA PRIVATE KEY-----")
    if start_index == -1 or end_index == -1:
        return None
    else:
        key_content = key[start_index:end_index]
        formatted_key = (
            "-----BEGIN RSA PRIVATE KEY-----\n" +
            key_content[len("-----BEGIN RSA PRIVATE KEY-----"):-len("-----END RSA PRIVATE KEY-----")] +
            "\n-----END RSA PRIVATE KEY-----\n"
        )
        return formatted_key
        

def join_hash(input_file, output_file):
    res=""
    rsa=False
    with open(input_file, 'r') as f:
        lines = f.readlines()
    
    one_line_hash = ''.join([line.strip() for line in lines])
    formatted_key = check_rsa(one_line_hash)
    
    if formatted_key is None:
        res=one_line_hash
    else:
        res=formatted_key
        rsa=True

    with open(output_file, 'w') as f:
        f.write(res)
    
    if rsa:
        print(f"rsa private key written in correct format to file: {output_file}")
    else:
        print(f"text written inline to file: {output_file}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: join_hash.py <input_file>")
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[1]
    join_hash(input_file, output_file)