#!/bin/bash

echo '314674' | sudo -S ip link set wlan0 down  2>&1                  
sudo iwconfig wlan0 mode managed 2>&1
sudo ip link set wlan0 up 2>&1

sudo airmon-ng stop wlan0mon > /dev/null 2>&1
sudo airmon-ng stop wlan0 > /dev/null 2>&1

sudo systemctl daemon-reload
sudo systemctl restart NetworkManager
sudo systemctl restart networking
sudo systemctl restart systemd-resolved 



