#!/bin/bash

if [ "$#" -lt 2 ]; then
    echo "Usage: $0 COMMAND EXPLAIN"
    exit 1
fi

first="$1"
chmod +x "$1"

# Shift to remove the first argument
shift

# Concatenate the first argument and the rest of the arguments
args="$1"
shift
while (( "$#" )); do
    args+=" $1"
    shift
done

echo "$first - $args" >> /home/yaniv/scripts-yaniv/myscripts.txt
sort /home/yaniv/scripts-yaniv/myscripts.txt -o tempfile.txt
mv tempfile.txt /home/yaniv/scripts-yaniv/myscripts.txt

# Move the file to /usr/local/bin only if there are additional arguments
if [ "$args" ]; then
    echo '314674' | sudo -S mv "$first" /usr/local/bin/
fi
