#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
    echo "Usage: $0 <hash_type> <wordlist> [hash_file]"
    exit 1
fi

# Assign command-line arguments to variables
type=$1
wordlist=$2
file=$3

# Use a default value if the hash file is not provided
if [ -z "$file" ]; then
    file="$HOME/hash.txt"
fi

# Run the hashcat command with the provided arguments
hashcat -a 0 -w 4 -O --status -m "$type" "$file" "$wordlist" 2>/dev/null

echo ""
echo "Last cracked passwords:"
tail -n 2 "$HOME/.local/share/hashcat/hashcat.potfile"
