#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "crack passwords from a hash"
    echo "Usage: $0 <hash_type> <wordlist>"
    exit 1
fi

# Assign command-line arguments to variables
type=$1
wordlist=$2

# Run the hashcat command with the provided arguments
john --wordlist=$wordlist  --format=$type ~/hash.txt --fork=32 --skip-self-test


echo ""
echo "last cracked:"
tail -n 2 $HOME/.john/john.pot
 
 