#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -lt 1 ] || [ "$#" -gt 2 ]; then
    echo "crack passwords from a gpg file"
    echo "Usage: $0 file.asc/file.gpg [wordlist]"
    exit 1
fi

filez=$1
wordlist=$2  #its an optional argument

gpg2john $filez > gpg.hash

if [ -n "$wordlist" ]; then
    john --wordlist=$wordlist gpg.hash --fork=32 --skip-self-test
else
    john gpg.hash --fork=32 --skip-self-test
fi

echo ""
echo "last cracked:"
tail -n 2 $HOME/.john/john.pot
 