#!/usr/bin/python3
import requests
from bs4 import BeautifulSoup
from urllib.parse import urlparse
import argparse
import sys

def get_subdomains(url):
    domain = urlparse(url).netloc
    allowed_domains = [domain]

    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    subdomains = set()
    for link in soup.find_all('a'):
        href = link.get('href')
        if href and href.startswith('http'):
            domain = urlparse(href).netloc
            subdomain = domain.split('.')[-2] + "." + domain.split('.')[-1]
            if any(domain.endswith(allowed_domain) for allowed_domain in allowed_domains):
                subdomains.add(subdomain)

    return subdomains


def get_folders(url):
    response = requests.get(url)
    soup = BeautifulSoup(response.content, 'html.parser')

    folders = set()
    for link in soup.find_all('a'):
        href = link.get('href')
        if href and not href.startswith('http'):
            folder = href.split('?')[0].split('#')[0].rsplit('/', 1)[0]
            if folder != "":
                folders.add(folder)

    return folders

if __name__ == '__main__':
        
    # Set up argument parsing
    parser = argparse.ArgumentParser(description='Scan a website for subdomains and folders - only if they appear in the HTML code.')
    parser.add_argument('url', help='The URL of the website to scan.')

    # Check if no arguments are passed and print help
    if len(sys.argv) == 1:
        parser.print_help(sys.stderr)
        sys.exit(1)

    # Parse arguments
    args = parser.parse_args()

    # Continue with your scanning logic
    url = args.url
    #print(f"Scanning {url} for subdomains and folders...")

    #url = args.url
    if not url.startswith(('http://', 'https://')):
        url = 'http://' + url

    subdomains = get_subdomains(url)
    folders = get_folders(url)

    print("\nSubdomains for", url, "are:\n")
    for subdomain in subdomains:
        print(subdomain)

    print("\nFolders for", url, "are:\n")
    for folder in folders:
        print(folder)
