#!/bin/bash

#this script assuming "l" alias to ls you can change as you need


location="."   
list_type="files"  

if [[ "$1" = "d" ]]; then
    list_type="dirs"  
elif [[ -n "$1" ]]; then
    location="$1"  
    if [[ "$2" = "d" ]]; then
        list_type="dirs"  
    fi
fi

cd "$location" || { echo "Failed to change directory to '$location'. Exiting."; exit 1; }

declare -a files
declare -a dirs

for item in *; do
    if [ -f "$item" ]; then
        files+=("$item")
        
    elif [ -d "$item" ]; then
        dirs+=("$item")
        
    fi
done

if [ "$list_type" = "dirs" ]; then
    for dir in "${dirs[@]}"; do
        lsd -ld --no-symlink --color=auto --icon=auto --icon-theme=unicode --group-dirs=first "$dir"
    done
else
    for file in "${files[@]}"; do
        lsd -l  --no-symlink --color=auto --icon=auto --icon-theme=unicode --group-dirs=first "$file"
    done
fi
