#!/bin/bash

# Check if the correct number of arguments is provided
if [ "$#" -lt 2 ] || [ "$#" -gt 3 ]; then
     echo "crack passwords of shadow file"
    echo "Usage: $0 passwd shadow <wordlist>"
    exit 1
fi

passwd=$1
shadow=$2
wordlist=$3 #its an optional argument

unshadow $passwd $shadow  > psw.shadow

if [ -n "$wordlist" ]; then
    john --wordlist=$wordlist psw.shadow --fork=32 --skip-self-test
else
    john psw.shadow --fork=32 --skip-self-test
fi

echo ""
echo "last cracked:"
tail -n 2 $HOME/.john/john.pot
 